### ISSUE TITLE
Cmd argument parsing library

### ISSUE THREAD

**Issue by jstuczyn** [nymtech/loopix-messaging#23]
Currently we are using `github.com/tav/golly/optparse` library for parsing command line arguments. However, the project doesn't seem to have been updated in over a year now and the repository itself is archived. Should we keep using it considering "it works" or should we switch to more modern solution? For reference Tendermint people (and actually a lot of Go projects from what I've seen) use combination of `https://github.com/spf13/viper` and `https://github.com/spf13/cobra`.

**Comment by futurechimp** [comment]
I used viper/cobra previously and felt that they worked well, but the `golly` code I quite like for the way it cleans things up. I can't remember though what the differences are (I might have been using Viper alone and finding that subcommands were a bit of a hassle).

I'd say let's leave it for now as an "it works". We can swap later for a maintained and documented lib.
